table dim_product
	lineageTag: 64f8f6ce-e8e8-4729-bca8-e5f0dd956ad3

	column 'Product Card Id'
		dataType: string
		lineageTag: 71c4c707-f96c-47e2-911d-de15c4a0aead
		summarizeBy: none
		sourceColumn: Product Card Id

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 8a4f7fc1-3c8b-49fe-88ed-99a3f10bc131
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column 'Product Price'
		dataType: double
		lineageTag: aa866a09-1551-4886-97b6-147ce9191383
		summarizeBy: none
		sourceColumn: Product Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Product Category'
		dataType: string
		lineageTag: 96de63e0-80cd-4d72-9bb5-f8ce942bf4d0
		summarizeBy: none
		sourceColumn: Product Category

		annotation SummarizationSetBy = Automatic

	partition dim_product = m
		mode: import
		queryGroup: 'dim & fact'
		source =
				let
				    Source = DataCoTransMain,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Product Card Id", "Product Name", "Product Price", "Product Category"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns")
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

